### ISSUE TITLE
Warning: Phalcon\Mvc\View\Engine\Volt\Compiler::compileFile(D:\wamp64\www\phalcon-chat/cache/volt/d__wamp64_www_phalcon-chat_app_views_chat_message.volt.php): failed to open stream: No such file or directory in D:\wamp64\www\phalcon-chat\public\index.php on line 35

### ISSUE THREAD

**Issue by harrywu001** [sintsov/phalcon-chat#1]
Warning: Phalcon\Mvc\View\Engine\Volt\Compiler::compileFile(D:\wamp64\www\phalcon-chat/cache/volt/d__wamp64_www_phalcon-chat_app_views_chat_message.volt.php): failed to open stream: No such file or directory in D:\wamp64\www\phalcon-chat\public\index.php on line 35 这个报错怎么解决？

**Comment by sintsov** [comment]
hello, i think the problem is related to file system permissions. You must set the group and user rights to write `phalcon-chat/cache/volt/`
